.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH JACTIMER 1 "August 12, 2010" "" "jactimer"

.SH NAME
jactimer \- a countdown timer

.SH SYNOPSIS
.B jactimer
.br

.SH DESCRIPTION
.B jactimer
is a gui countdown timer written in C++ using the Qt framework. It uses the phonon backend to play an audio file or start a programm after the countdown has finished. Window decorations are hidden by default to use up as little desktop space as possible. The system tray icon is animated to indicate the timer's current progress.
.br
Visit http://www.jactimer.org/
.PP

.SH FILES
.I ~/.config/jactimer/jactimer.conf
.RS
Configuration file
.RE
.I /usr/share/pixmaps/jactimer.xpm
.RS
Low quality xpm-icon
.RE
.I /usr/share/icons/hicolor/48x48/apps/jactimer.png
.RS
The jactimer icon
.RE
.I /usr/share/applications/jactimer.desktop
.RS
freedesktop.org desktop file
.RE

.SH AUTHORS
.B jactimer
was written by Thomas Trapp in 2010
